modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    logoFile="logo.png"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
	modId="immersiveengineering"
	mandatory=true
	versionRange="[1.19.2-9.2.2-165,)"
	ordering="BEFORE"
	side="BOTH"

[[dependencies.${mod_id}]]
	modId="jei"
	mandatory=false
	versionRange="[11.2.0.246,)"
	ordering="BEFORE"
	side="CLIENT"